assignment2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main.views import add_product_ajax, create_product_flutter, get_product_json, show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user, delete, increment, decrement, edit

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create_item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete/<int:id>', delete, name='delete'),
    path('increment/<int:id>', increment, name='increment'),
    path('decrement/<int:id>', decrement, name='increment'),
    path('edit/<int:id>', edit, name='edit'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    category = models.TextField()
    power = models.IntegerField()
    rating = models.IntegerField(default=0)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description", "category", "power"]

main/views.py
import datetime
import json
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotFound, HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.core import serializers
from main.forms import ItemForm
from main.models import Item
from django.views.decorators.csrf import csrf_exempt


@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    data_count = items.count()

    context = {
        'application_name': 'RAF Inventory',
        'name': request.user.username,
        'class': 'PBP KKI',
        'items': items,
        'data_count': data_count,
        'last_login': request.COOKIES['last_login']
        if 'last_login' in request.COOKIES.keys()
        else "",
    }

    return render(request, 'main.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)
    
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def delete(request, id):
    item = Item.objects.get(pk=id)
    item.delete()
    return redirect('main:show_main')

def increment(request, id):
    item = Item.objects.get(pk=id)
    item.amount += 1
    item.save()
    return redirect('main:show_main')

def decrement(request, id):
    item = Item.objects.get(pk=id)
    if item.amount > 0:
        item.amount += -1
        item.save()
    else:
        item.amount = 0
    return redirect('main:show_main')

def edit(request, id):
    item = Item.objects.get(pk = id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    
    context = {'form': form}
    return render(request, "edit_item.html", context)

def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        category = request.POST.get("category")
        power = request.POST.get("power")
        rating = request.POST.get("rating")
        user = request.user

        new_product = Item(name=name, amount=amount, description=description, category=category, power=power, user=user, rating=rating)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"],
            category = data["category"],
            power = int(data["power"])
            )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap');
    html * {
        font-family: 'Poppins', sans-serif;
    }
    </style>

<h1 style="color: blue;">Add New Item</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% include 'navbar.html' %}

<style>
.gradient-custom {
    /* fallback for old browsers */
    background: #14bdff;
    
    /* Chrome 10-25, Safari 5.1-6 */
    background: -webkit-linear-gradient(to right, rgb(255, 0, 0), rgb(0, 0, 255));
    
    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(to right, rgb(255, 0, 0), rgb(0, 0, 255))
    }
</style>

<section class="vh-120 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
              <div class="mb-md-5 mt-md-4 pb-5">
                
                <h2 class="fw-bold mb-2">Edit Item</h2>
                <p class="text-white-50 mb-5">You can freely edit item in this inventory!</p>
                
                <form method="POST" action="#">
                    {% csrf_token %}
                        <div class="form-outline form-white mb-4">
                            <input type="text" name="name" class="form-control form-control-lg" maxlength="255" required id="id_name" value="{{form.instance.name}}"/>
                            <label class="form-label" for="id_name">Name</label>
                            </div>
        
                        <div class="form-outline form-white mb-4">
                            <input type="number" name="amount" id="id_amount" class="form-control form-control-lg" required value="{{form.instance.amount}}"/>
                            <label class="form-label" for="id_amount">Amount</label>
                            </div>
                        
                        <div class="form-outline form-white mb-4">
                            <textarea name="description" cols="20" rows="10" required="" id="id_description" data-gramm="false" wt-ignore-input="true" class="form-control form-control-lg">{{form.instance.description}}</textarea>
                            <label class="form-label" for="id_description">Description</label>
                            </div>
                        
                        <div class="form-outline form-white mb-4">
                            <textarea name="category" cols="40" rows="10" required="" id="id_category" data-gramm="false" wt-ignore-input="true" class="form-control form-control-lg">{{form.instance.category}}</textarea>
                            <label class="form-label" for="id_category">Category</label>
                            </div>
                        
                        <div class="form-outline form-white mb-4">
                            <input type="number" name="power" id="id_power" class="form-control form-control-lg" required value="{{form.instance.power}}"/>
                            <label class="form-label" for="id_power">Power</label>
                            </div>
        
                        <input class="btn btn-outline-light btn-lg px-5" type="submit" value="Edit Item"/>
                    </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
 .gradient-custom-2 {
    /* fallback for old browsers */
    background: #5f5dff;
    
    /* Chrome 10-25, Safari 5.1-6 */
    background: -webkit-linear-gradient(to right, #0000ff, #ff0000);
    
    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(to right, #0000ff, #ff0000);
    }
    
    @media (min-width: 768px) {
    .gradient-form {
    height: 100vh !important;
    }
    }
    @media (min-width: 769px) {
    .gradient-custom-2 {
    border-top-right-radius: .3rem;
    border-bottom-right-radius: .3rem;
    }
    }
</style>

<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body p-md-5 mx-md-4">
  
                  <div class="text-center">
                    <h4 class="mt-1 mb-5 pb-1">RAF Item Storage</h4>
                  </div>
  
                  <form method="POST" action="">
                    {% csrf_token %}
  
                    <div class="form-outline mb-4">
                        <input type="text" name="username" placeholder="Username" class="form-control">
                      <label class="form-label" for="form2Example11">Username</label>
                    </div>
  
                    <div class="form-outline mb-4">
                        <input type="password" name="password" placeholder="Password" class="form-control"></td>
                      <label class="form-label" for="form2Example22">Password</label>
                    </div>
  
                    <div class="text-center pt-1 mb-5 pb-1">
                      <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit" value="Login">Log
                        in</button>
                    </div>
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">Don't have an account?</p>
                      <a class="btn btn-outline-danger" href="{% url 'main:register' %}">Register</a>
                    </div>
  
                  </form>
  
                </div>
              </div>
              <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                  <h4 class="mb-3">Welcome to RAF Item Storage</h4>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}

<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap');
    html * {
        font-family: 'Poppins', sans-serif;
    }
    table {
    border-collapse: collapse;
    width: 80%;
    margin: 20px auto; 
    }

    td, th {
    border: 2px solid black;
    padding: 10px;
    text-align: center;
    background-color: rgb(206, 221, 255);
    }

    th {
    background-color: #0000ff;
    }

    body {
    background-color: rgb(255, 255, 255);
    margin: 0;
    padding: 0;
    text-align: center;
    }

    h1, h5, p {
    padding-left: 20px;
    margin: 10px 0; /* Berikan margin atas dan bawah yang lebih besar pada elemen-elemen ini */
    text-align: left;
    }
    </style>

<h1 style="color: #0000ff;">RAF Inventory</h1> <hr>

<h5>Account:</h5>
<p>{{ name }}</p>

<h3 style="text-align: center; color: #0000ff;">Inventory</h3>

<table id="product_table"></table>

<br />

<p style="text-align: center; padding-right: 20px;">Items in Inventory: {{ data_count }}</p>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="category" class="col-form-label">Category:</label>
                        <textarea class="form-control" id="category" name="category"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="power" class="col-form-label">Power:</label>
                        <input type="number" class="form-control" id="power" name="power"></input>
                    </div>
                    <div class="mb-3">
                        <label for="rating" class="col-form-label">Rating:</label>
                        <input type="number" class="form-control" id="rating" name="rating"></input>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product</button>

<p style="text-align: right; padding-right: 10px ;">RAF Inventory</p>
<p>Last login session: {{ last_login }}</p>

<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        const productTable = document.getElementById("product_table");
        productTable.innerHTML = "";

        const products = await getProducts();
        let htmlString = "<div class='row'>";  // Start a new row

        products.forEach((item, index) => {
            if (index % 3 === 0 && index !== 0) {
                htmlString += "</div><div class='row'>";  // Close previous row and start a new row for every 3 cards
            }
            
            if (item.fields.rating == 4) {
                htmlString += `
                    <div class="col-md-4">
                        <div class="card-item" style="background-color: rgb(0,0,255);">
                            <div class="card mx-auto p-3" style="width: 18rem;">
                                <div class="card-body">
                                    <h2 class="card-title">${item.fields.name}</h2>
                                    <p class="card-text">Amount: ${item.fields.amount}</p>
                                    <p class="card-text">${item.fields.description}</p>
                                    <p class="card-text">Category: ${item.fields.category}</p>
                                    <p class="card-text">Price: ${item.fields.power}</p>
                                    <a style="justify-content: baseline;" href='edit/${item.pk}' class="btn btn-outline-warning" onclick="editItem(${item.pk})">Edit</a>
                                    <button style="justify-content: baseline;" class="btn btn-outline-danger" onclick="deleteProduct(${item.pk})">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>`;
            } else if (item.fields.rating == 3) {
                htmlString += `
                    <div class="col-md-4">
                        <div class="card-item" style="background-color: rgb(0,255,0);">
                            <div class="card mx-auto p-3" style="width: 18rem;">
                                <div class="card-body">
                                    <h2 class="card-title">${item.fields.name}</h2>
                                    <p class="card-text">Amount: ${item.fields.amount}</p>
                                    <p class="card-text">${item.fields.description}</p>
                                    <p class="card-text">Category: ${item.fields.category}</p>
                                    <p class="card-text">Price: ${item.fields.power}</p>
                                    <a style="justify-content: baseline;" href='edit/${item.pk}' class="btn btn-outline-warning" onclick="editItem(${item.pk})">Edit</a>
                                    <button style="justify-content: baseline;" class="btn btn-outline-danger" onclick="deleteProduct(${item.pk})">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>`;
            }

            else if (item.fields.rating == 2) {
                htmlString += `
                    <div class="col-md-4">
                        <div class="card-item" style="background-color: rgb(255,255,0);">
                            <div class="card mx-auto p-3" style="width: 18rem;">
                                <div class="card-body">
                                    <h2 class="card-title">${item.fields.name}</h2>
                                    <p class="card-text">Amount: ${item.fields.amount}</p>
                                    <p class="card-text">${item.fields.description}</p>
                                    <p class="card-text">Category: ${item.fields.category}</p>
                                    <p class="card-text">Price: ${item.fields.power}</p>
                                    <a style="justify-content: baseline;" href='edit/${item.pk}' class="btn btn-outline-warning" onclick="editItem(${item.pk})">Edit</a>
                                    <button style="justify-content: baseline;" class="btn btn-outline-danger" onclick="deleteProduct(${item.pk})">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>`;
            }
            else if (item.fields.rating == 1) {
                htmlString += `
                    <div class="col-md-4">
                        <div class="card-item" style="background-color: rgb(255,0,0);">
                            <div class="card mx-auto p-3" style="width: 18rem;">
                                <div class="card-body">
                                    <h2 class="card-title">${item.fields.name}</h2>
                                    <p class="card-text">Amount: ${item.fields.amount}</p>
                                    <p class="card-text">${item.fields.description}</p>
                                    <p class="card-text">Category: ${item.fields.category}</p>
                                    <p class="card-text">Price: ${item.fields.power}</p>
                                    <a style="justify-content: baseline;" href='edit/${item.pk}' class="btn btn-outline-warning" onclick="editItem(${item.pk})">Edit</a>
                                    <button style="justify-content: baseline;" class="btn btn-outline-danger" onclick="deleteProduct(${item.pk})">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>`;
            }
            else if (item.fields.rating == 0) {
                htmlString += `
                    <div class="col-md-4">
                        <div class="card-item" style="background-color: rgb(255,0,255);">
                            <div class="card mx-auto p-3" style="width: 18rem;">
                                <div class="card-body">
                                    <h2 class="card-title">${item.fields.name}</h2>
                                    <p class="card-text">Amount: ${item.fields.amount}</p>
                                    <p class="card-text">${item.fields.description}</p>
                                    <p class="card-text">Category: ${item.fields.category}</p>
                                    <p class="card-text">Price: ${item.fields.power}</p>
                                    <a style="justify-content: baseline;" href='edit/${item.pk}' class="btn btn-outline-warning" onclick="editItem(${item.pk})">Edit</a>
                                    <button style="justify-content: baseline;" class="btn btn-outline-danger" onclick="deleteProduct(${item.pk})">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>`;
            }
        });

        htmlString += "</div>";  // Close the last row
        productTable.innerHTML = htmlString;
        document.getElementById("item_count").innerHTML = `Items in Inventory: ${ items.length }`
    }

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    function editProduct(productId) {
        fetch(`{% url 'main:edit' 0 %}${productId}/`, {
        method: "POST",
        body: new FormData(document.querySelector('#form'))
    }).then(refreshProducts)

    document.getElementById("form").reset()
    return false
    }

    function deleteProduct(productId) {
        fetch(`{% url 'main:delete' 0 %}`.replace("0", productId), {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    refreshProducts()
    document.getElementById("button_add").onclick = addProduct
</script>
{% endblock content %}

main/templates/navbar.html
{% block content %}
<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #0000ff;
    }
    li {
        float: left;
    }
    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }
    li a:hover {
        background-color: #27a1ff;
    }
    .navbar-text {
        color: white;
        padding: 14px 16px;
    }
</style>

<ul>
    <li><a href="/">Home</a></li>
    <li class="navbar-text">Welcome to RAF Inventory</li>
    <li style="float:right"><a class="active" href="{% url 'main:logout' %}">Logout</a></li>
</ul>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
<style>
 .gradient-custom-2 {
    /* fallback for old browsers */
    background: #5f5dff;
    
    /* Chrome 10-25, Safari 5.1-6 */
    background: -webkit-linear-gradient(to right, #0000ff, #ff0000);
    
    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(to right, #0000ff, #ff0000);
    }
    
    @media (min-width: 768px) {
    .gradient-form {
    height: 100vh !important;
    }
    }
    @media (min-width: 769px) {
    .gradient-custom-2 {
    border-top-right-radius: .3rem;
    border-bottom-right-radius: .3rem;
    }
    }
</style>

<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body p-md-5 mx-md-4">
  
                  <div class="text-center">
                    <h4 class="mt-1 mb-5 pb-1">Register Account</h4>
                  </div>
  
                  <form method="POST" action="">
                    {% csrf_token %}
  
                    <div class="form-outline mb-4">
                        <input type="text" name="username" maxlength="150" class="form-control" autocapitalize="none" autocomplete="username" autofocus required id="id_username">
                      <label class="form-label" for="id_username">Username</label>
                    </div>
  
                    <div class="form-outline mb-4">
                        <input type="password" name="password1" class="form-control" autocomplete="new-password" required id="id_password1" aria-autocomplete="list"></td>
                      <label class="form-label" for="id_password1">Password</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="password" name="password2" class="form-control" autocomplete="new-password" required id="id_password2"></td>
                      <label class="form-label" for="id_password2">Password Confirmation</label>
                    </div>
  
  
                    <div class="text-center pt-1 mb-5 pb-1">
                      <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit" value="Register">Register</button>
                    </div>
  
  
                  </form>
  
                </div>
              </div>
              <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                  <h4 class="mb-3">RAF Inventory</h4>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}